# Generated by Django 4.1.4 on 2023-11-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcomment',
            old_name='user_id',
            new_name='user_created_id',
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='text',
            field=models.TextField(),
        ),
    ]
