version: '3'

services:
  database:
    build: ./database
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: manage_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  django:
    build: ./django
    ports:
      - "8001:8001"
    command: python3 manage.py runserver 0.0.0.0:8001