# Generated by Django 4.1.4 on 2023-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdepartment',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
