# Generated by Django 4.1.4 on 2023-11-26 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_masterdepartment_datetime_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterDepartment',
        ),
    ]
