"""exclude tables4

Revision ID: 84c0ae3e1e2a
Revises: 067c4afe2d8a
Create Date: 2023-11-23 00:40:04.273399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c0ae3e1e2a'
down_revision: Union[str, None] = '067c4afe2d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
