"""exclude tables5

Revision ID: 9aaa2e0a6ba3
Revises: 84c0ae3e1e2a
Create Date: 2023-11-23 00:41:12.250085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaa2e0a6ba3'
down_revision: Union[str, None] = '84c0ae3e1e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
