# Generated by Django 4.1.4 on 2023-11-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('datetime_order', models.DateTimeField()),
                ('date_due', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
